version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 

  express:
    build:
      context: ./backend # Ensure this points to the correct backend folder
      dockerfile: Dockerfile # Ensure this file exists
    ports:
      - "3000:3000" 

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
 
